---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-app-mriyam-com-v1alpha1-podset
  failurePolicy: Fail
  name: mpodset.kb.io
  rules:
  - apiGroups:
    - app.mriyam.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - podsets
  sideEffects: None
