# permissions for end users to edit daemonjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: daemonjob-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: daemonjob
    app.kubernetes.io/part-of: daemonjob
    app.kubernetes.io/managed-by: kustomize
  name: daemonjob-editor-role
rules:
- apiGroups:
  - batch.mriyam.com
  resources:
  - daemonjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.mriyam.com
  resources:
  - daemonjobs/status
  verbs:
  - get
