# permissions for end users to edit humans.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: human-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: human
    app.kubernetes.io/part-of: human
    app.kubernetes.io/managed-by: kustomize
  name: human-editor-role
rules:
- apiGroups:
  - mammals.mriyam.com
  resources:
  - humans
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mammals.mriyam.com
  resources:
  - humans/status
  verbs:
  - get
